name: flutter_native
description: A new Flutter package for managing UI&#x2F;UX natively for both Android and iOS platform.
version: 0.0.1
homepage: https://github.com/eyro-labs/flutter_native

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  platform: ^3.0.0

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
