import 'package:flutter/material.dart' as material;
import 'package:flutter/rendering.dart';

class NativeListTile extends material.ListTile {
  const NativeListTile({
    material.Key? key,
    material.Widget? leading,
    material.Widget? title,
    material.Widget? subtitle,
    material.Widget? trailing,
    bool isThreeLine = false,
    bool? dense,
    material.VisualDensity? visualDensity,
    material.ShapeBorder? shape,
    material.EdgeInsetsGeometry? contentPadding,
    bool enabled = true,
    material.GestureTapCallback? onTap,
    material.GestureLongPressCallback? onLongPress,
    MouseCursor? mouseCursor,
    bool selected = false,
    material.Color? focusColor,
    material.Color? hoverColor,
    material.FocusNode? focusNode,
    bool autofocus = false,
    material.Color? tileColor,
    material.Color? selectedTileColor,
    bool? enableFeedback,
    double? horizontalTitleGap,
    double? minVerticalPadding,
    double? minLeadingWidth,
  })  : assert(!isThreeLine || subtitle != null),
        super(
          key: key,
          leading: leading,
          title: title,
          subtitle: subtitle,
          trailing: trailing,
          isThreeLine: isThreeLine,
          dense: dense,
          visualDensity: visualDensity,
          shape: shape,
          contentPadding: contentPadding,
          enabled: enabled,
          onTap: onTap,
          onLongPress: onLongPress,
          mouseCursor: mouseCursor,
          selected: selected,
          focusColor: focusColor,
          hoverColor: hoverColor,
          focusNode: focusNode,
          autofocus: autofocus,
          tileColor: tileColor,
          selectedTileColor: selectedTileColor,
          enableFeedback: enableFeedback,
          horizontalTitleGap: horizontalTitleGap,
          minVerticalPadding: minVerticalPadding,
          minLeadingWidth: minLeadingWidth,
        );
}
